---
- name: Clone dotfiles repo from github
  become: true
  become_user: "{{ var_current_user }}"
  ansible.builtin.git:
    repo: "{{ var_dotfiles_git_repository }}"
    dest: "{{ var_home_dir }}/.dotfiles"

- name: Remove files from "$HOME"
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ var_current_user }}/.profile"
    - "{{ var_current_user }}/.bash_logout"
    - "{{ var_current_user }}/.bashrc"

- name: Stow dotfiles
  become: true
  become_user: "{{ var_current_user }}"
  ansible.builtin.shell:
    cmd: "stow -d {{ var_home_dir }}/.dotfiles -t {{ var_home_dir }} {{ item }}"
  loop: "{{ stow }}"
