---
- name: Install "podman" packages
  ansible.builtin.apt:
    name: '{{ item }}'
  loop:
    - podman
    - podman-compose

- name: Copy subuid files for podman rootless
  ansible.builtin.copy:
    dest: /etc/subuid
    content: "{{ var_current_user }}:100000:65536"

- name: Copy subgid files for podman rootless
  ansible.builtin.copy:
    dest: /etc/subgid
    content: "{{ var_current_user }}:100000:65536"

- name: Configure podman registries
  ansible.builtin.copy:
    src: registries.conf
    dest: /etc/containers/
