---
- name: Detect if running on laptop
  stat:
    path: /sys/module/battery
  register: laptop

- name: Install package tlp (optimize linux laptop battery life)
  ansible.builtin.apt:
    name: tlp
  notify: restart tlp
  when: laptop.stat.islnk is defined
