---
- name: Install audio server and applications
  ansible.builtin.apt:
    name: '{{ item }}'
  loop:
      - pavucontrol
      - cava
      - pipewire
      - pipewire-pulse
      - playerctl
      - wireplumber
      - mpd
      - mpc
      - ncmpcpp
