---
- name: Install virtual machine packages
  ansible.builtin.apt:
    name: '{{ item }}'
  loop:
    - qemu-system
    - libvirt-daemon-system
    - virt-manager
    - vagrant
    - packer
    - pkg-config
  notify: Restart libvirt

- name: Add user to libvirt group
  ansible.builtin.user:
    name: '{{ var_current_user }}'
    groups: libvirt
    append: yes

- name: Enable nested virtualization
  ansible.builtin.copy:
    dest: /etc/modprobe.d/kvm.conf
    content: |
      options kvm_intel nested=1

- name: Create isos directory
  become: true
  ansible.builtin.file:
    path:  "{{ var_home_dir }}/isos"
    owner: "{{ var_current_user }}"
    group: "{{ var_current_user }}"
    state: directory
    mode: '0770'
