---
- name: Install common packages
  ansible.builtin.apt:
    pkg:
      - p7zip-full
      - autoconf
      - automake
      - apt-file
      - apt-transport-https
      - build-essential
      - bash-completion
      - bat
      - bc
      - bind9-dnsutils
      - borgbackup
      - btop
      - catdoc
      - curl
      - cmake
      - docx2txt
      - dosfstools
      - duf
      - exa
      - exfatprogs
      - exif
      - fd-find
      - sshfs
      - fzf
      - git
      - gnupg2
      - highlight
      - htop
      - inetutils-telnet
      - iucode-tool
      - inxi
      - jq
      - lf
      - firmware-linux
      - lm-sensors
      - lshw
      - lsof
      - lsscsi
      - mediainfo
      - mtr
      - ncdu
      - neofetch
      - neovim
      - newsboat
      - netcat-openbsd
      - net-tools
      - nfs-common
      - nmon
      - nmap
      - ntfs-3g
      - odt2txt
      - pciutils
      - pkg-config
      - python3-pip
      - python3-venv
      - qrencode
      - ripgrep
      - smartmontools
      - stow
      - sudo
      - tmux
      - trash-cli
      - tree
      - tty-clock
      - tcpdump
      - unrar-free
      - unzip
      - urlview
      - urlscan
      - youtube-dl
      - w3m
      - wget
      - whois
      - xz-utils
      - zoxide
    state: present

- name: Create symbolic link for fd
  ansible.builtin.file:
    src: /usr/bin/fdfind
    dest: /usr/bin/fd
    owner: root
    group: root
    state: link

- name: Create symbolic link for bat
  ansible.builtin.file:
    src: /usr/bin/batcat
    dest: /usr/bin/bat
    owner: root
    group: root
    state: link

- name: Check if "broot" already exists
  stat:
    path: /usr/local/bin/broot
  register: file_broot

- name: Download and install broot (better tree)
  ansible.builtin.get_url:
    url: https://dystroy.org/broot/download/x86_64-linux/broot
    dest: /usr/local/bin/broot
    mode: "777"
  when: not file_broot.stat.exists

- name: Add an apt signing key for "glow" (markdown viewer)
  ansible.builtin.apt_key:
    url: https://repo.charm.sh/apt/gpg.key
    keyring: /etc/apt/trusted.gpg.d/glow.gpg
    state: present

- name: Add apt-source for "glow" (markdown viewer)
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/trusted.gpg.d/glow.gpg] https://repo.charm.sh/apt/ * *"
    state: present

- name: Check installed packages
  package_facts:
    manager: auto

- name: Install obsidian from github (note taking app)
  ansible.builtin.apt:
    deb: https://github.com/obsidianmd/obsidian-releases/releases/download/v{{ obsidian.version }}/obsidian_{{ obsidian.version }}_amd64.deb
  when: "'obsidian' not in ansible_facts.packages"